import requests, re
from bs4 import BeautifulSoup

response = requests.get("http://www.ufcstats.com/fighter-details/59a9d6dac61c2540")

testSoup = BeautifulSoup(response.content, 'html.parser')

def extractFighterName(soup):
    '''Identifies fighter history to be parsed.
       Args:
            soup(BeautifulSoup object): BeautifulSoup object must originate from the ufcstats.com section '''
    
    name = soup.find('span', attrs={'class': re.compile('b-content__title-highlight')})
    
    return name.text.strip()

def extractFighterRecord(soup):
    '''Extracts each fighter's fighting record from the soup entered
       Args: 

            soup: unmodified BeautifulSoup object initialized via fighter url ran through soup_generator()'''
    
    record = soup.findChildren('span', attrs={'class': re.compile('b-content__title-record')})
    
    return record[0].text.strip().split(':')[1].strip()

def createFighterBasicStatsSoup(soup):
    
    basic_stats_soup = soup.findChildren('li', attrs={'class': re.compile('b-list')})
    
    return basic_stats_soup

def extractBasicStatsHeight(soup):
    '''Extracts fighter height from modified soup object included as argument.
           Args:  
            base_stats object generated by generate_basic_stats_soup()'''
    basic_stats_soup = createFighterBasicStatsSoup(soup)
    #feet
    height = basic_stats_soup[0].text.strip().split(':')[1].strip().split(' ')[0].replace("'", "")
    return height


testHeight = extractBasicStatsHeight(testSoup)
print('test', createFighterBasicStatsSoup(testSoup))

