import requests, re
from bs4 import BeautifulSoup

def SLpM(base_stats):
    
    '''Initializes a soup object that isolates significant strikes landed per minute.
    Args: 
        base_stats: object generated by generate_basic_stats_soup()'''

    SLpM = base_stats[5].text.split(':')[1].replace('%', '').strip()
    
    if SLpM == '--':
        return None
    
    else:
        SLpM = float(SLpM)
        return SLpM

def StrAcc(base_stats):
    
    '''Initializes a soup object that isolates significant striking accuracy.
    Args: 
        base_stats: object generated by generate_basic_stats_soup()'''   
    
    StrAcc =  base_stats[6].text.split(':')[1].replace('%', '').strip()
    
    if StrAcc == '--':
        return None 
    
    else:
        StrAcc = float(StrAcc)
        return StrAcc

def SApM(base_stats):
    
    '''Initializes a soup object that isolates significant strikes absorbed per minute.
    Args: 
        base_stats: object generated by generate_basic_stats_soup()'''
    
    SApM = base_stats[7].text.split(':')[1].strip()
    
    if SApM == '--':
        return None
    
    else:
        SApM = float(SApM)
        return SApM

def StrDef(base_stats):
    
    '''Initializes a soup object that isolates significant strike defence.
    Args: 
        base_stats: object generated by generate_basic_stats_soup()'''
    
    StrDef = base_stats[8].text.split(':')[1].replace('%', '').strip()
    
    if StrDef == '--':
        return None
    
    else:
        StrDef = float(StrDef)
        return StrDef

def TDAvg(base_stats):
    
    '''Initializes a soup object that isolates average takedown per 15 minutes.
    Args:
        base_stats: object generated by generate_basic_stats_soup()'''
    
    TDAvg = base_stats[10].text.split(':')[1].strip()
    
    if TDAvg == '--':
        return None
    
    else:
        TDAvg = float(TDAvg)
        return TDAvg

def TDAcc(base_stats):
    
    '''Initializes a soup object that isolates takedown accuracy.
    Args: 
        base_stats: object generated by generate_basic_stats_soup()'''
    
    TDAcc = base_stats[11].text.split(':')[1].strip().replace('%', '')
    
    if TDAcc == '--':
        return None
    
    else: 
        TDAcc = float(TDAcc)
        return TDAcc

def TDDef(base_stats):
    
    '''Initializes a soup object that isolates takedown defense.
    Args: 
        base_stats: object generated by generate_basic_stats_soup()'''
    
    TDDef = base_stats[12].text.split(':')[1].replace('%', '').strip()
    
    if TDDef == '--': 
        return None
    
    else:
        TDDef = float(TDDef)
        return TDDef

def SubAvg(base_stats):
    
    '''Initializes a soup object that isolates average submission attempts per 15.
    Args: 
        base_stats: object generated by generate_basic_stats_soup()'''
    
    SubAvg =  base_stats[13].text.split(':')[1].strip().replace('%', '')  
    
    if SubAvg == '--':  
        return None
    
    else:
        SubAvg = float(SubAvg)
        return SubAvg