import requests, re
from bs4 import BeautifulSoup

# Construction of Fighter Physical Statistics DataFrame 

def fighter_name(soup):
    '''Identifies fighter history to be parsed.

        Args:
    
            soup(BeautifulSoup object): BeautifulSoup object must originate from a urls hosting fighter profiles'''
    
    name = soup.find('span', attrs={'class': re.compile('b-content__title-highlight')})
    
    return name.text.strip()

def fighter_record(soup):
    '''Extracts each fighter's fighting record from the soup entered
    
        Args: 
    
            soup: unmodified BeautifulSoup object initialized via fighter url ran through soup_generator()'''
    
    record = soup.findChildren('span', attrs={'class': re.compile('b-content__title-record')})
    
    return record[0].text.strip().split(':')[1].strip()

def basic_stats_height(base_stats):
    '''Extracts fighter height from modified soup object included as argument.
    
        Args: 
            
            base_stats object generated by generate_basic_stats_soup()'''
    
    #feet
    height = base_stats[0].text.strip().split(':')[1].strip().split(' ')[0].replace("'", "")
    
   #inches
    if height == '--':
        
        return height
    
    else:
        
        height = int(height)
        
        inches = int(base_stats[0].text.strip().split(':')[1].strip().split(' ')[1].replace("'", "").replace('"', '').replace("--", "0"))

        height_to_inches = (height * 12) 
    
        final_height = height_to_inches + inches
    
        return int(final_height)

def basic_stats_weight(base_stats):
    '''Extracts fighter weight from modified soup object included as argument.
    
        Args: 
    
            base_stats: object generated by generate_basic_stats_soup()'''
    
    weight = base_stats[1].text.strip().split(':')[1].strip().replace(' lbs.', '')
    
    if weight == '--':
        
        return weight
    
    else:
        
        weight = int(weight)        
        
    return weight 

def basic_stats_reach(base_stats):
    '''Extracts fighter reach from modified soup object included as argument.
    
        Args: 
    
            base_stats: object generated by generate_basic_stats_soup()'''
    
    reach = base_stats[2].text.strip().split(':')[1].strip().replace('"', '')
    
    if reach == '--':
        
        return reach
    
    else:
        
        reach = int(reach)
        
    return reach

def basic_stats_stance(base_stats):
    '''Extracts fighter stance from modified soup object included as argument.
    
        Args: 
    
            base_stats: object generated by generate_basic_stats_soup()'''
    stance = base_stats[3].text.strip().split(':')[1].strip()
    
    return stance

def basic_stats_DOB(base_stats):
    '''Extracts fighter DOB from modified soup object included as argument.
    
        Args: 
    
            base_stats: object generated by generate_basic_stats_soup()'''
    DOB = base_stats[4].text.strip().split(':')[1].strip()
    
    return DOB

